import libs += libsfml-graphics%lib{sfml-graphics}

./ : exe{example-island} exe{example-joystick} exe{example-opengl} exe{example-shader}

exe{example-island}: island/cxx{*} island/hxx{*.h} island/resources/file{*} $libs
exe{example-joystick}: joystick/cxx{*} joystick/resources/file{*} $libs
exe{example-opengl}: opengl/cxx{*} opengl/resources/file{*} $libs
exe{example-shader}: shader/{hxx cxx}{*} shader/resources/file{*} $libs
